%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                                                                          %
%          Generated by MATLAB 9.11 and Fixed-Point Designer 7.3           %
%                                                                          %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%#codegen
function gram=mimo_gram_fixpt(H)
fm = get_fimath();

H1=fi(H, 1, 16, 13, fm);
H2=fi(H', 1, 16, 13, fm);
Hi1=fi(imag(H2), 1, 16, 13, fm);
Hr1=fi(real(H2), 1, 16, 13, fm);
Hi2=fi(imag(H1), 1, 16, 13, fm);
Hr2=fi(real(H1), 1, 16, 13, fm);
G_tmp=fi(zeros(64,1,'like',H(1)), 1, 16, 12, fm);
gram=fi(zeros(8,8,'like',H(1)), 1, 16, 8, fm);
for x=1:8
    for y=1:8
        for n=1:64
            a=fi(Hr1(x,n), 1, 16, 13, fm);b=fi(Hi1(x,n), 1, 16, 13, fm);
            c=fi(Hr2(n,y), 1, 16, 13, fm);d=fi(Hi2(n,y), 1, 16, 13, fm);
            t1=fi(a*c, 1, 16, 12, fm);
            t2=fi(b*d, 1, 16, 12, fm);
            t3=fi(a*d, 1, 16, 13, fm);
            t4=fi(c*b, 1, 16, 13, fm);
            G_tmp(n)=t1-t2+(t3+t4)*fi(1i, 0, 1, 0, fm);
            gram(x,y)=gram(x,y)+G_tmp(n);
        end
    end
end
end


function fm = get_fimath()
	fm = fimath('RoundingMethod', 'Floor',...
	     'OverflowAction', 'Wrap',...
	     'ProductMode','FullPrecision',...
	     'MaxProductWordLength', 128,...
	     'SumMode','FullPrecision',...
	     'MaxSumWordLength', 128);
end
