%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                                                                          %
%          Generated by MATLAB 9.11 and Fixed-Point Designer 7.3           %
%                                                                          %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%#codegen
function gram=mimo_gram_fixpt(H)
fm = get_fimath();

H1=fi(H, 1, 16, 8, fm);
H2=fi(H', 1, 16, 8, fm);
Hi1=fi(imag(H2), 1, 16, 8, fm);
Hr1=fi(real(H2), 1, 16, 8, fm);
Hi2=fi(imag(H1), 1, 16, 8, fm);
Hr2=fi(real(H1), 1, 16, 8, fm);
gram=fi(zeros(8,8,'like',H(1)),1,16,8,fm);
G_tmp=fi(zeros(64,1,'like',H(1)),1,16,8,fm);
for x=1:8
    for y=1:8
        for n=1:64
            a=fi(Hr1(x,n), 1, 16, 13, fm);b=fi(Hi1(x,n), 1, 16, 8, fm);
            c=fi(Hr2(n,y), 1, 16, 13, fm);d=fi(Hi2(n,y), 1, 16, 8, fm);
            t1=fi(a*c, 1, 16, 12, fm);t1x=t1.hex;disp(t1x)
            t2=fi(b*d, 1, 16, 12, fm);t2x=t2.hex;disp(t2x)
            t3=fi(a*d, 1, 16, 13, fm);t3x=t3.hex;disp(t3x)
            t4=fi(c*b, 1, 16, 13, fm);t4x=t4.hex;disp(t4x)
            t5=fi(t1-t2,1,16,8,fm);t5x=t5.hex;disp(t5x)
            t6=fi(t3+t4,1,16,8,fm);t6x=t6.hex;disp(t6x)
            G_tmp(n)=fi(t5+t6*fi(1i, 0, 1, 0, fm),1,16,8,fm);
        end 
        gram(x,y)=sum(G_tmp(:));
    end
end
    I1=reshape(Hi1,512,1);
I2=I1.bin;
R1=reshape(Hr1,512,1);
R2=R1.bin;
writematrix(R2,'R.txt')
writematrix(I2,'I.txt')
writematrix(gram.hex,'Gout.txt')
end


function fm = get_fimath()
	fm = fimath('RoundingMethod', 'Floor',...
	     'OverflowAction', 'Wrap',...
	     'ProductMode','FullPrecision',...
	     'MaxProductWordLength', 128,...
	     'SumMode','FullPrecision',...
	     'MaxSumWordLength', 128);
end
