%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                                                                          %
%          Generated by MATLAB 9.11 and Fixed-Point Designer 7.3           %
%                                                                          %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%#codegen
function gram=mimo_gram_fixpt1(H)
fm = get_fimath();

H1=fi(H, 1, 16, 8, fm);
H2=fi(H', 1, 16, 8, fm);
Hi1=fi(imag(H2), 1, 16, 8, fm);
Hr1=fi(real(H2), 1, 16, 8, fm);
Hi2=fi(imag(H1), 1, 16, 8, fm);
Hr2=fi(real(H1), 1, 16, 8, fm);
G_tmp=fi(zeros(64,1,'like',H(1)), 1, 16, 11, fm);
gram=fi(zeros(8,8,'like',H(1)), 1, 16, 8, fm);
for x=1:8
    for y=1:8
        for n=1:64
            t1=fi(Hr1(x,n).*Hr2(n,y), 1, 16, 12, fm);%t1x=t1.hex;
            t2=fi(Hi1(x,n).*Hi2(n,y), 1, 16, 12, fm);%t2x=t2.hex;
            t3=fi(Hr1(x,n).*Hi2(n,y), 1, 16, 13, fm);%t3x=t3.hex;
            t4=fi(Hi1(x,n).*Hr2(n,y), 1, 16, 13, fm);%t4x=t4.hex;
            t5=fi(t1-t2,1,16,8,fm);%t5x=t5.hex;
            t6=fi(t3+t4,1,16,8,fm);%t6x=t6.hex;
            G_tmp(n)=fi(t5,1,16,8,fm)+fi(t6,1,16,8,fm)*fi(1i, 0, 1, 0, fm);%Gx=G_tmp.hex;
            gram(x,y)=fi(gram(x,y)+G_tmp(n),1,16,8,fm);
        end
         
    end
end


I1=reshape(Hi1,512,1);
I2=I1.bin;
R1=reshape(Hr1,512,1);
R2=R1.bin;
writematrix(R2,'R.txt')
writematrix(I2,'I.txt')
writematrix(gram.hex,'Gout.txt')

 end
function fm = get_fimath()
	fm = fimath('RoundingMethod', 'Floor',...
	     'OverflowAction', 'Wrap',...
	     'ProductMode','FullPrecision',...
	     'MaxProductWordLength', 128,...
	     'SumMode','FullPrecision',...
	     'MaxSumWordLength', 128);
end
